### ISSUE TITLE
Project structure in Utilities/Bus

### ISSUE THREAD

**Issue by raphaelzulliger** [evelix/IDesign-VirtualTradeMe#2]
Hi

Not sure someone looks at these issues - but I try my luck anyway :-)

I'm building a project following The Method, based on .NET6. Therefore, WCF is absent. I anyway don't have WCF knowledge other than having read most of Juval's WCF book. Beside this, I have to start by using a proprietary Message Broker. However, I think that's not too relevant.

My question is: I really don't understand the structure in `Utitilities/Bus`: Why is it split among the different layers? I would have expected to have a "Bus" and probably a "Test" project, while the former would provide some classed to create connection to the message bus, send and receive messages, etc. What kind of classes/APIs are expected to be inside the Bus directory? (An example would probably be most useful for me)

Thanks in advance!

**Comment by joerglang** [comment]
Hi Raphael

You are right, the splitting below the utilities doesn't make sense. In one symstem that I designed according to the Method I have a Bus utility that basically abstracts the code to connect to the RabbitMq service bus and some helper methods. No need to split further.

I created this project to get the "feeling" how a project structure looks like in "real life". I was in contact with Monty at that time and he helped me shape it out.
So the design is a good starting point to venture out on your own, but as you have discovered is not bullet proof.

**Comment by raphaelzulliger** [comment]
Thank for the answer, Joerg!

I love this repo, I'm visiting it over and over again.

I'm *not* going to promise anything, but *if* I'd create PRs to cleanup/enhance things a bit, would you be willing to "discuss" on them and eventually merge or do you prefer to not spend any time on this?

**Comment by joerglang** [comment]
Sure we can put a bit of work into it to make it more real.
